# Bernoulli Naive Bayes Explanation

## Sample Data

In [1]:
SAMPLE_TRAIN = [
    "The quick brown fox jumps over the lazy dog.",
    "The sky is blue and the sun is shining.",
    "Cats are wonderful pets to have around the house.",
    "Soccer is a popular sport played all around the world.",
    "Pizza topped with cheese and pepperoni is my favorite.",
    "Learning a new language can be challenging but rewarding.",
    "Reading books is a great way to expand your knowledge.",
    "The internet has revolutionized the way we communicate.",
    "Music has the power to evoke strong emotions in people.",
    "Exercise is important for maintaining good health.",
    "Science has made incredible advancements in recent years.",
    "Coffee is the fuel that keeps many people going throughout the day.",
    "Traveling allows you to experience different cultures and cuisines.",
    "The importance of education cannot be overstated.",
    "Technology continues to progress at a rapid pace.",
    "Dogs are known for their loyalty and companionship.",
    "Cooking homemade meals can be a fun and rewarding activity.",
    "Nature has a way of calming the mind and soothing the soul.",
    "Artistic expression comes in many forms, from painting to music.",
    "Happiness is often found in the simplest of things."
]

SAMPLE_TRAIN_Y = [1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0]

SAMPLE_TEST = [
    "TF-IDF, short for term frequency-inverse document frequency, is a numerical statistic that reflects the importance of a word in a document relative to a collection of documents or a corpus.",
    "The TF-IDF value increases proportionally to the number of times a word appears in the document and is offset by the number of documents in the corpus that contain the word.",
    "TF-IDF is commonly used in information retrieval and text mining as a weighting factor for scoring the relevance of a word to a document in a corpus.",
    "The intuition behind TF-IDF is that words that occur frequently in a document but rarely in the corpus are more important in describing the content of the document.",
    "In contrast, words that occur frequently in both the document and the corpus are less important as they are likely to be common words with less discriminative power.",
    "To calculate the TF-IDF score for a word in a document, you multiply the term frequency (TF) by the inverse document frequency (IDF).",
    "TF is the frequency of a term in a document, while IDF is the logarithmically scaled inverse fraction of the documents that contain the word.",
    "By weighting the TF by IDF, the TF-IDF score penalizes words that are common across documents and emphasizes words that are unique to a specific document.",
    "Once you have computed the TF-IDF scores for all words in a document, you can represent the document as a vector where each dimension corresponds to a word and the value corresponds to its TF-IDF score.",
    "TF-IDF vectorization is a fundamental step in many natural language processing tasks, such as document classification, clustering, and information retrieval."
]


## TF-IDF

### Scikit Learn Implementation

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd

sklearn_tfidf = TfidfVectorizer(norm=None)

sklearn_tfidf

/tmp/ipykernel_45952/3485358109.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


TfidfVectorizer(norm=None)

In [3]:
sklearn_result = sklearn_tfidf.fit_transform(SAMPLE_TRAIN)

  (0, 111)	2.0
  (0, 93)	1.0
  (0, 12)	1.0
  (0, 43)	1.0
  (0, 62)	1.0
  (0, 81)	1.0
  (0, 67)	1.0
  (0, 30)	1.0
  (1, 111)	2.0
  (1, 102)	1.0
  (1, 61)	2.0
  (1, 10)	1.0
  (1, 4)	1.0
  (1, 108)	1.0
  (1, 100)	1.0
  (2, 111)	1.0
  (2, 17)	1.0
  (2, 5)	1.0
  (2, 121)	1.0
  (2, 87)	1.0
  (2, 115)	1.0
  (2, 52)	1.0
  (2, 6)	1.0
  (2, 55)	1.0
  (3, 111)	1.0
  :	:
  (17, 79)	1.0
  (17, 77)	1.0
  (17, 14)	1.0
  (17, 74)	1.0
  (17, 104)	1.0
  (17, 105)	1.0
  (18, 115)	1.0
  (18, 75)	1.0
  (18, 58)	1.0
  (18, 72)	1.0
  (18, 7)	1.0
  (18, 38)	1.0
  (18, 21)	1.0
  (18, 41)	1.0
  (18, 44)	1.0
  (18, 84)	1.0
  (19, 111)	1.0
  (19, 61)	1.0
  (19, 58)	1.0
  (19, 79)	1.0
  (19, 50)	1.0
  (19, 80)	1.0
  (19, 42)	1.0
  (19, 101)	1.0
  (19, 113)	1.0


In [4]:
print(sklearn_result)

  (0, 30)	3.3513752571634776
  (0, 67)	3.3513752571634776
  (0, 81)	3.3513752571634776
  (0, 62)	3.3513752571634776
  (0, 43)	3.3513752571634776
  (0, 12)	3.3513752571634776
  (0, 93)	3.3513752571634776
  (0, 111)	3.2932543298501047
  (1, 100)	3.3513752571634776
  (1, 108)	3.3513752571634776
  (1, 4)	2.09861228866811
  (1, 10)	3.3513752571634776
  (1, 61)	3.930161792087174
  (1, 102)	3.3513752571634776
  (1, 111)	3.2932543298501047
  (2, 55)	3.3513752571634776
  (2, 6)	2.9459101490553135
  (2, 52)	3.3513752571634776
  (2, 115)	2.09861228866811
  (2, 87)	3.3513752571634776
  (2, 121)	3.3513752571634776
  (2, 5)	2.9459101490553135
  (2, 17)	3.3513752571634776
  (2, 111)	1.6466271649250523
  (3, 122)	3.3513752571634776
  :	:
  (17, 77)	3.3513752571634776
  (17, 79)	2.6582280766035327
  (17, 51)	2.435084525289323
  (17, 118)	2.6582280766035327
  (17, 4)	2.09861228866811
  (17, 111)	3.2932543298501047
  (18, 84)	3.3513752571634776
  (18, 44)	3.3513752571634776
  (18, 41)	3.3513752571634776


In [5]:
len(sklearn_tfidf.vocabulary_)

126

In [6]:
sklearn_tfidf.vocabulary_

{'the': 111,
 'quick': 93,
 'brown': 12,
 'fox': 43,
 'jumps': 62,
 'over': 81,
 'lazy': 67,
 'dog': 30,
 'sky': 102,
 'is': 61,
 'blue': 10,
 'and': 4,
 'sun': 108,
 'shining': 100,
 'cats': 17,
 'are': 5,
 'wonderful': 121,
 'pets': 87,
 'to': 115,
 'have': 52,
 'around': 6,
 'house': 55,
 'soccer': 103,
 'popular': 90,
 'sport': 106,
 'played': 89,
 'all': 2,
 'world': 122,
 'pizza': 88,
 'topped': 116,
 'with': 120,
 'cheese': 19,
 'pepperoni': 86,
 'my': 76,
 'favorite': 39,
 'learning': 68,
 'new': 78,
 'language': 66,
 'can': 15,
 'be': 9,
 'challenging': 18,
 'but': 13,
 'rewarding': 98,
 'reading': 95,
 'books': 11,
 'great': 49,
 'way': 118,
 'expand': 36,
 'your': 125,
 'knowledge': 64,
 'internet': 60,
 'has': 51,
 'revolutionized': 97,
 'we': 119,
 'communicate': 22,
 'music': 75,
 'power': 91,
 'evoke': 34,
 'strong': 107,
 'emotions': 33,
 'in': 58,
 'people': 85,
 'exercise': 35,
 'important': 57,
 'for': 40,
 'maintaining': 71,
 'good': 48,
 'health': 53,
 'science': 9

In [7]:
vocabulary = sklearn_tfidf.get_feature_names_out()
sentence_indices = [30, 67, 81, 62, 43, 12, 93, 111]
vocabulary[[sentence_indices]]
pd.DataFrame({
  'text': vocabulary[sentence_indices],
  'index': sentence_indices,
})

text  index
0    dog     30
1   lazy     67
2   over     81
3  jumps     62
4    fox     43
5  brown     12
6  quick     93
7    the    111

In [8]:
SAMPLE_TEST_TRANSFORMED = sklearn_tfidf.transform(SAMPLE_TEST)

### 1. Count Vocabulary

In [9]:
import re

# Lowercase text
preprocess_train = [
  text.lower()
  for text 
  in SAMPLE_TRAIN
]

# Remove punctuation
preprocess_train = [
  re.sub(r'[^\w\s]', '', text)
  for text
  in preprocess_train
]

In [10]:
# Add unique word to set
UNIQUE_WORDS = set()

for sample in preprocess_train:
  for word in sample.split(' '):
    # Only add unique words of 2 or more characters
    # SKLearn instead uses this regex pattern when
    # processing text:
    # r”(?u)\b\w\w+\b”
    if len(word) < 2: continue
    UNIQUE_WORDS.add(word)

In [11]:
UNIQUE_WORDS

{'activity',
 'advancements',
 'all',
 'allows',
 'and',
 'are',
 'around',
 'artistic',
 'at',
 'be',
 'blue',
 'books',
 'brown',
 'but',
 'calming',
 'can',
 'cannot',
 'cats',
 'challenging',
 'cheese',
 'coffee',
 'comes',
 'communicate',
 'companionship',
 'continues',
 'cooking',
 'cuisines',
 'cultures',
 'day',
 'different',
 'dog',
 'dogs',
 'education',
 'emotions',
 'evoke',
 'exercise',
 'expand',
 'experience',
 'expression',
 'favorite',
 'for',
 'forms',
 'found',
 'fox',
 'from',
 'fuel',
 'fun',
 'going',
 'good',
 'great',
 'happiness',
 'has',
 'have',
 'health',
 'homemade',
 'house',
 'importance',
 'important',
 'in',
 'incredible',
 'internet',
 'is',
 'jumps',
 'keeps',
 'knowledge',
 'known',
 'language',
 'lazy',
 'learning',
 'loyalty',
 'made',
 'maintaining',
 'many',
 'meals',
 'mind',
 'music',
 'my',
 'nature',
 'new',
 'of',
 'often',
 'over',
 'overstated',
 'pace',
 'painting',
 'people',
 'pepperoni',
 'pets',
 'pizza',
 'played',
 'popular',
 'powe

In [12]:
UNIQUE_WORDS == set(sklearn_tfidf.vocabulary_.keys())

True

In [13]:
# Make our dictionaries
WORD_TO_INDEX = {}
INDEX_TO_WORD = {}

for index, word in enumerate(sorted(list(UNIQUE_WORDS))):
  WORD_TO_INDEX[word] = index
  INDEX_TO_WORD[index] = word

In [14]:
WORD_TO_INDEX

{'activity': 0,
 'advancements': 1,
 'all': 2,
 'allows': 3,
 'and': 4,
 'are': 5,
 'around': 6,
 'artistic': 7,
 'at': 8,
 'be': 9,
 'blue': 10,
 'books': 11,
 'brown': 12,
 'but': 13,
 'calming': 14,
 'can': 15,
 'cannot': 16,
 'cats': 17,
 'challenging': 18,
 'cheese': 19,
 'coffee': 20,
 'comes': 21,
 'communicate': 22,
 'companionship': 23,
 'continues': 24,
 'cooking': 25,
 'cuisines': 26,
 'cultures': 27,
 'day': 28,
 'different': 29,
 'dog': 30,
 'dogs': 31,
 'education': 32,
 'emotions': 33,
 'evoke': 34,
 'exercise': 35,
 'expand': 36,
 'experience': 37,
 'expression': 38,
 'favorite': 39,
 'for': 40,
 'forms': 41,
 'found': 42,
 'fox': 43,
 'from': 44,
 'fuel': 45,
 'fun': 46,
 'going': 47,
 'good': 48,
 'great': 49,
 'happiness': 50,
 'has': 51,
 'have': 52,
 'health': 53,
 'homemade': 54,
 'house': 55,
 'importance': 56,
 'important': 57,
 'in': 58,
 'incredible': 59,
 'internet': 60,
 'is': 61,
 'jumps': 62,
 'keeps': 63,
 'knowledge': 64,
 'known': 65,
 'language': 66,
 

In [15]:
sklearn_tfidf.vocabulary_ == WORD_TO_INDEX

True

In [16]:
INDEX_TO_WORD

{0: 'activity',
 1: 'advancements',
 2: 'all',
 3: 'allows',
 4: 'and',
 5: 'are',
 6: 'around',
 7: 'artistic',
 8: 'at',
 9: 'be',
 10: 'blue',
 11: 'books',
 12: 'brown',
 13: 'but',
 14: 'calming',
 15: 'can',
 16: 'cannot',
 17: 'cats',
 18: 'challenging',
 19: 'cheese',
 20: 'coffee',
 21: 'comes',
 22: 'communicate',
 23: 'companionship',
 24: 'continues',
 25: 'cooking',
 26: 'cuisines',
 27: 'cultures',
 28: 'day',
 29: 'different',
 30: 'dog',
 31: 'dogs',
 32: 'education',
 33: 'emotions',
 34: 'evoke',
 35: 'exercise',
 36: 'expand',
 37: 'experience',
 38: 'expression',
 39: 'favorite',
 40: 'for',
 41: 'forms',
 42: 'found',
 43: 'fox',
 44: 'from',
 45: 'fuel',
 46: 'fun',
 47: 'going',
 48: 'good',
 49: 'great',
 50: 'happiness',
 51: 'has',
 52: 'have',
 53: 'health',
 54: 'homemade',
 55: 'house',
 56: 'importance',
 57: 'important',
 58: 'in',
 59: 'incredible',
 60: 'internet',
 61: 'is',
 62: 'jumps',
 63: 'keeps',
 64: 'knowledge',
 65: 'known',
 66: 'language',
 

In [17]:
from collections import Counter
from scipy.sparse import csr_matrix

# The three axes of our matrix
row = []
column = []
value = []

for index, sample in enumerate(preprocess_train):

  # Get the count of every word in each sample
  word_count = dict(Counter(sample.split(' ')))

  for word, count in word_count.items():
    # Finding the vocab index of each word in the sample
    # This will represent the column to add the count to
    vocab_index = WORD_TO_INDEX.get(word)

    # When word is found in vocabulary
    if vocab_index is not None:
      # Determines what's added to the matrix
      # Let the matrix shape be (x, y)
      # At a certain index common to all
      # it will add the sample index to the row (x)
      # then it will add which column the value will be (y)
      # And it tells what is the value, the count, to be added at position (x, y)
      # when we append value
      row.append(index)
      column.append(vocab_index)
      value.append(count)

In [18]:
VOCABULARY = csr_matrix(
  (value, (row, column)),
  shape=(len(preprocess_train), len(WORD_TO_INDEX))
)

In [19]:
print(VOCABULARY)

  (0, 12)	1
  (0, 30)	1
  (0, 43)	1
  (0, 62)	1
  (0, 67)	1
  (0, 81)	1
  (0, 93)	1
  (0, 111)	2
  (1, 4)	1
  (1, 10)	1
  (1, 61)	2
  (1, 100)	1
  (1, 102)	1
  (1, 108)	1
  (1, 111)	2
  (2, 5)	1
  (2, 6)	1
  (2, 17)	1
  (2, 52)	1
  (2, 55)	1
  (2, 87)	1
  (2, 111)	1
  (2, 115)	1
  (2, 121)	1
  (3, 2)	1
  :	:
  (17, 77)	1
  (17, 79)	1
  (17, 104)	1
  (17, 105)	1
  (17, 111)	2
  (17, 118)	1
  (18, 7)	1
  (18, 21)	1
  (18, 38)	1
  (18, 41)	1
  (18, 44)	1
  (18, 58)	1
  (18, 72)	1
  (18, 75)	1
  (18, 84)	1
  (18, 115)	1
  (19, 42)	1
  (19, 50)	1
  (19, 58)	1
  (19, 61)	1
  (19, 79)	1
  (19, 80)	1
  (19, 101)	1
  (19, 111)	1
  (19, 113)	1


### Term Frequency

TF(t) = (number of times term t appears in a document) / (total number of terms in a document)

### Document Frequency

In [20]:
# Count number of times a term at a given vocab index
# occurred in the input
DOCUMENT_FREQUENCY = np.bincount(
  VOCABULARY.indices,
  minlength=VOCABULARY.shape[1]
)

In [21]:
DOCUMENT_FREQUENCY

array([ 1,  1,  1,  1,  6,  2,  2,  1,  1,  3,  1,  1,  1,  1,  1,  2,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        4,  1,  1,  1,  1,  1,  1,  4,  1,  1,  7,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  2,  1,  1,  2,  1,  1,  1,  3,  1,  1,  1,  1,  1,
        2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, 10,  1,  1,  1,  6,  1,  1,  3,
        1,  1,  1,  1,  1,  1,  1])

In [22]:
# Proof of doc frequency

print(DOCUMENT_FREQUENCY[4]) # -> 6
print(INDEX_TO_WORD[4]) # -> and

word_count = 0
for text in preprocess_train:
  for term in text.split():
    if term == INDEX_TO_WORD[4]:
      word_count += 1
word_count == DOCUMENT_FREQUENCY[4] # -> True

6
and


True

In [23]:
# Smooth document frequency by adding 1 to doc freq
# Prevents zero division
# Note that this can be seen in index 0, for example

NUM_OF_SAMPLES, NUM_OF_TERMS = VOCABULARY.shape

DOCUMENT_FREQUENCY_SMOOTH = DOCUMENT_FREQUENCY + 1
NUM_OF_SAMPLES_SMOOTH = NUM_OF_SAMPLES + 1

In [24]:
DOCUMENT_FREQUENCY_SMOOTH

array([ 2,  2,  2,  2,  7,  3,  3,  2,  2,  4,  2,  2,  2,  2,  2,  3,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  3,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        5,  2,  2,  2,  2,  2,  2,  5,  2,  2,  8,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  3,  2,  2,  3,  2,  2,  2,  4,  2,  2,  2,  2,  2,
        3,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2, 11,  2,  2,  2,  7,  2,  2,  4,
        2,  2,  2,  2,  2,  2,  2])

### Inverse Document Frequency

IDF(t) = log(total number of documents) / (number of documents with term t in it)

In [25]:
IDF = np.log(NUM_OF_SAMPLES_SMOOTH / DOCUMENT_FREQUENCY_SMOOTH) + 1

In [26]:
IDF == sklearn_tfidf.idf_

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [27]:
import scipy.sparse as sp

IDF_SPARSE_MATRIX = sp.diags(
  IDF,
)


In [28]:
TFIDF_RESULT = VOCABULARY * IDF_SPARSE_MATRIX

In [29]:
print(TFIDF_RESULT)

  (0, 111)	3.2932543298501047
  (0, 93)	3.3513752571634776
  (0, 81)	3.3513752571634776
  (0, 67)	3.3513752571634776
  (0, 62)	3.3513752571634776
  (0, 43)	3.3513752571634776
  (0, 30)	3.3513752571634776
  (0, 12)	3.3513752571634776
  (1, 111)	3.2932543298501047
  (1, 108)	3.3513752571634776
  (1, 102)	3.3513752571634776
  (1, 100)	3.3513752571634776
  (1, 61)	3.930161792087174
  (1, 10)	3.3513752571634776
  (1, 4)	2.09861228866811
  (2, 121)	3.3513752571634776
  (2, 115)	2.09861228866811
  (2, 111)	1.6466271649250523
  (2, 87)	3.3513752571634776
  (2, 55)	3.3513752571634776
  (2, 52)	3.3513752571634776
  (2, 17)	3.3513752571634776
  (2, 6)	2.9459101490553135
  (2, 5)	2.9459101490553135
  (3, 122)	3.3513752571634776
  :	:
  (17, 79)	2.6582280766035327
  (17, 77)	3.3513752571634776
  (17, 74)	3.3513752571634776
  (17, 51)	2.435084525289323
  (17, 14)	3.3513752571634776
  (17, 4)	2.09861228866811
  (18, 115)	2.09861228866811
  (18, 84)	3.3513752571634776
  (18, 75)	2.9459101490553135
  (

In [30]:
np.array_equal(TFIDF_RESULT.toarray(), sklearn_result.toarray())

True

## Bernoulli Naive Bayes

### Scikit Learn Implementation

In [31]:
from sklearn.naive_bayes import BernoulliNB

sklearn_nb = BernoulliNB()
sklearn_nb

BernoulliNB()

In [32]:
sklearn_nb.fit(TFIDF_RESULT, SAMPLE_TRAIN_Y)

BernoulliNB()

In [33]:
sklearn_nb.predict(SAMPLE_TEST_TRANSFORMED)

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0])

### Custom

In [34]:
from collections import defaultdict

class CustomBernoulliNB():
  def __init__(self, alpha=1.0):
    # Smoothing parameter
    # Used to prevent features from being totally 0 when getting feature counts
    # Essentially tells NB that there's an extra count to all features
    # which would otherwise zero things when in the case that a feature
    # when predicting was not learned from fitting
    self.alpha = alpha

  def fit(self, X, y):
    if X.shape[0] != len(y):
      print("ERROR: X and y have different lengths")
      return

    num_of_samples = X.shape[0]

    X = X.toarray()

    # Turn counts into binary values
    # NOTE: This is the assumption of Bernoulli NB
    X = np.where(X != 0, 1, 0)

    # Group X by class
    # Use a default dict for this. This automatically makes a list
    # when it encounters a key that is unknown. So we can iterate over
    # each X and y, and append to the list of each respective class
    grouped = defaultdict(list)

    for X_sample, y_sample in zip(X, y):
      grouped[y_sample].append(X_sample)

    # Fixes bug where classes were inverted
    # in the event that the first y sample
    # is 1 instead of 0
    ordered_keys = sorted(grouped.keys())

    # STEP 1: Getting prior log probability of each class
    # Essentially, the (log) probability of class being 0 or 1 based on train set
    # Log scale is used to prevent underflow due to lack of floating point precision
    # Equation: Number of samples in class / number of overall samples
    # If there are 10 samples, 4 are 0 and 6 are 1
    # The equation then looks like
    # np.log(4/10) for 0
    # np.log(6/10) for 1
    self.class_log_prior_ = [
      np.log(len(grouped[data_class]) / num_of_samples)
      for data_class
      in ordered_keys
    ]
    # Output: array([-0.70126153, -0.68509814])
    # These are log probabilities. To reverse this, we can use np.exp()
    # and the result after np.exp() is
    # Output: array([0.49595924, 0.50404076])
    # This is the same as:
    # 11292 / (11476 + 11292)
    # 11476 / (11476 + 11292)
    # We will consistently use these log probabilities elsewhere in calculations

    # STEP 2: Count each word in each class. Add smoothing parameter (self.alpha)
    # The smoothing parameter is important to prevent divison by 0
    # Make a list so it's easy to append to, numpy arrays are annoying to make 2D arrays
    # from several 1D arrays
    word_count_per_class = []

    # Iterate over each class (0, then 1)
    for data_class in ordered_keys:
      # Sum the count of every word occurrence by column, going downward
      # So if the array looks something like
      # [[1 2 3]
      #  [2 3 4]
      #  [3 4 5]]
      # sum(axis=0) will turn this into
      # [6, 9, 12]
      count_in_class = np.array(grouped[data_class]).sum(axis=0)

      word_count_per_class.append(count_in_class)
    # Make a final array by joining together the 2 lists to make it 2D
    # then we add the alpha value to everything
    # This alpha is important to prevent division by 0. You can observe this
    # by setting the alpha to 0. You will get a lot of nan values
    word_count_per_class = np.array(word_count_per_class) + self.alpha

    # Reshape to make it a 2D array where the sum corresponds to the row of a class
    # [[223218], -> 0
    #  [225122]] -> 1
    sum_of_words_in_each_class = word_count_per_class.sum(axis=1).reshape(-1, 1)

    # STEP 3: Calculate log probability of each word
    # NOTE: Not actually used in BNB
    self.feature_log_prob_ = np.log(word_count_per_class / sum_of_words_in_each_class)

    # STEP 4: BNB
    # Smoothing parameter for classes
    # Multiplied by 2 because of 2 classes, 0 and 1
    smoothing = 2 * self.alpha
    
    # Add the smoothing to number of documents
    num_of_documents_with_smoothing = np.array([
      len(grouped[data_class]) + smoothing
      for data_class 
      in ordered_keys
    ])

    # STEP 5: Feature Probabilities
    # (Word count in class [0 or 1] + alpha) / (value count [11292, 11476] + alpha * 2)
    # Given an alpha of 1,
    # If you plug in 1.77085178e-04 * 11294, you get 1.999~. This means the original word
    # appeared once (2 - alpha = 1) in the 0 class
    self.feature_prob_ = word_count_per_class / num_of_documents_with_smoothing.reshape(-1, 1)

    return self
  
  def predict_log_proba(self, X):
    """
    This function gets the numerator part of Bernoulli NB
    Read carefully
    """
    X = X.toarray()
    # Turn counts into binary values
    X = np.where(X != 0, 1, 0)

    samples = []
    for sample in X:
      # This part is solving for the numerator
      # For each sample of data,
      # Sum the log probabilities of all the features that appear in the class
      # and add that to the log probabilities that the features do not appear in the class
      # then add once again to the log probability of the class (this is the class prior)
      negative_prob = 1 - self.feature_prob_

      # Invert from 0 to 1, or 1 to 0
      inverted_sample = np.abs(sample - 1)

      # We multiply feature prob to sample to essentially
      # zero out all features that do not appear
      # This leaves us with the features that appear as the only nonzero values
      # so we can simply add them; this is the same as
      # multiplying all the probabilities of all the features
      # but we can just add because we use the log scale
      # The inverted probabilities are based on the Bernoulli rule
      # P(x_i∣y) = P(i∣y)x_i + (1 − P(i∣y)) * (1 − x_i)
      # sample probabilities = P(i∣y)x_i
      # and the inverted probabilities represent the 
      # (1 − P(i∣y)) * (1 − x_i)
      # portion
      sample_probabilities = np.log(self.feature_prob_) * sample
      inverted_probabilities = np.log(negative_prob) * inverted_sample

      log_sum_of_probabilities = (sample_probabilities + inverted_probabilities).sum(axis=1)
      feature_probabilities_with_class_prior = log_sum_of_probabilities + self.class_log_prior_
      samples.append(feature_probabilities_with_class_prior)
    return np.array(samples)
    
  def predict_proba(self, X):
    # Get the numerator part
    outputs = self.predict_log_proba(X)
    
    results = []
    for data_class in outputs:
      # The following two lines are a manual implementation
      # of the logsumexp function
      # The main purpose is to prevent numerical underflow
      # in the denominator due to the need for summation in the formula
      # Reference: https://stats.stackexchange.com/questions/105602/example-of-how-the-log-sum-exp-trick-works-in-naive-bayes
      output_max = data_class.max()
      logsumexp_result = output_max + np.log(np.sum(np.exp(data_class - output_max)))

      results.append(logsumexp_result)
    results = np.array(results).reshape(-1, 1)

    return np.exp(outputs - results)

  def predict(self, X):
    outputs = self.predict_log_proba(X)

    return np.argmax(outputs, axis=1)


In [35]:
custom_nb = CustomBernoulliNB()

In [36]:
custom_nb.fit(TFIDF_RESULT, SAMPLE_TRAIN_Y)

In [44]:
np.array_equal(custom_nb.predict(SAMPLE_TEST_TRANSFORMED), sklearn_nb.predict(SAMPLE_TEST_TRANSFORMED))

True